sonar.projectKey=frontend-app
sonar.projectName=Frontend App
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.login=sqa_2998c5640d25f96acfccb342b3d2f98b4f979498
